#!/usr/bin/python3
# SPDX-FileCopyrightText: 2025 Ryomu Inukai
# SPDX-License-Identifier: BSD-3-Clause
import sys

def tonum(s)
    try:
        return int(s)
    except:
        return float(s)

ams = 0
for line in sys.stdin:
    line = line.rstrip()
    ans += tonum(line)

print(ans)
