name: test
on: push
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run test
        run: |
          chmod +x factorize test.bash
          ./test.bash
